### PR TITLE
remove use of static keys and use IAM roles instead

### PR DESCRIPTION
**Pull request by thiagonache**
Using static keys is not best practice on AWS. It is going to force SDK to use the OS configuration or attached role.

### CODE REVIEW

**Comment by marek-obuchowicz** [comment]
:+1: great as this will use default SDK client behaviour and allow flexibility in providing credentials

**Comment by thiagonache** [comment]
Let's see if the code owner agrees with it @Thomas-Gelf

**Comment by mxhash** [comment]
Hi,

thanks for the PR. We would make the IAM Role as a default but have also the key feature. Many users have the module not running in the web and rely on the default behaviour.

Cheers,
Marius

**Comment by thiagonache** [comment]
@mxhash 
it is frustrating that you guys even asked for keep both options. icinga and this plugin are awesome, but I'd like to follow security best practices.

**Comment by mxhash** [comment]
But you can now, don't you? I've used your PR as a base to keep both of the options. As far as I understand, you need either a SAML Foundation or Web needs to run within AWS. In the most cases this is not available in setups. Also we can't drop existing configurations.

thanks again for your PR!

Regards,
Marius

**Pull request closed without merging**
