### PR TITLE
Add support for new metadata, importsource tweak

### LINKED ISSUE #2: Filters Expression in sync rule not working
Hello! We would like to use some filters in order to not import all hosts so when I tried to test filter expresion in sync rule nothing happens i think is not working.

screenshot at 13-32-23
After saving this change nothing happens
screenshot at 13-32-36

Very thankfull,
Jon

### PR DESCRIPTION
**Pull request by mbassett**
Add support for new information from ec2 instance metadata

Tweak importsource to also set tags.{key} variables for use in sync filters.

Fixes #2  and #5

### CODE REVIEW

**Comment by mbassett** [comment]
image

now the tags.{key} values are populated in preview view, and available for use in filters

**Comment by mbassett** [comment]
I thought this fixed it for sync filters, but it seems to have only fixed the preview display tab. 

:'(

**Comment by mbassett** [comment]
So far as I can tell...

filters that work:
name
private_ip
image

filters that don't work:
tags.Name
tags.*
vpc_id
private_dns
state


I even tried adding new fields name_tag and asg_group_tag  and those also did not work in filters  (and yes i added them to the ImportSource.php also )

                $this->extractTags($entry, $object);
                $object->name_tag = $object->tags->{'Name'};
                if (isset($object->tags->{'aws:autoscaling:groupName'})) {
                    $object->asg_group_tag = $object->tags->{'aws:autoscaling:groupName'};
                }

**Comment by mbassett** [comment]
@Thomas-Gelf   Can you tell me why this isn't working?   I see values in the import source preview page, but they do not seem to be applying in the sync role.   


specifically  283da03c2f58db79d7514d9e1bc158f45fded839    and the other minor commits around it?

I see the value for disabled = 1   for hosts that are not in running state, but the sync rule does not disable them.

image

**Comment by walterheck** [comment]
@dnsmichi @Thomas-Gelf Can this be merged please?

**Comment by Thomas-Gelf** [comment]
@walterheck: sure! I'll check whether this is still necessary...

```patch
             $result->tags->{$t['Key']} = $t['Value'];
+            // so we can use these tags in the expected way in import filters via tags.attribute
+            $result->{'tags.'.$t['Key']} = $t['Value'];
```

...as in the meantime there should have been a related change in Director itself. The rest looks good! Sorry for the delay @mbassett, this got completely forgotten.

Cheers,
Thomas

**Comment by lippserd** [comment]
Since #18 has been merged, I close this as duplicate. Thanks for your efforts though!

**Pull request closed without merging**
